Swap node-fetch for isomorphic-fetch
perf-goggles would cause test failures when running tests under the js-perf-dashboard project
(first project to use perf-goggles) with the failure:

> ReferenceError: fetch is not defined